[build]
#rustc-wrapper = "/usr/local/cargo/bin/sccache"
incremental = false
target-dir = "/target"
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[profile.docker]
inherits = "release"
incremental = false
target-dir = "/target"
debug-assertions = false
opt-level = 1
debug = "line-tables-only"