[package]
name = "stackify-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stackify"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
color-eyre = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
bollard = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
libc = { workspace = true }
signal-hook = { workspace = true }
tempfile = { workspace = true }
pathdiff = { workspace = true }
time  = { workspace = true }
shellwords = { workspace = true }
rand = { workspace = true }
console = { workspace = true }
#crossterm = { workspace = true }
#ratatui = { workspace = true }
comfy-table = { workspace = true }
indicatif = "0.17.8"
diesel = { workspace = true }
diesel_migrations = { workspace = true }
stackify-common = { path = "../stackify-common" }
anstyle = { workspace = true }
home = { workspace = true }
colorchoice = "1.0.0"
dyn-fmt = "0.4.0"
futures-util = { workspace = true }
regex = { workspace = true }