[package]
name = "stackify-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stackify"
path = "src/main.rs"

[dependencies]
# Util
rand = { workspace = true }
time  = { workspace = true }
libc = { workspace = true }
signal-hook = { workspace = true }
tempfile = { workspace = true }
pathdiff = { workspace = true }
home = { workspace = true }
dyn-fmt = "0.4.0"
regex = { workspace = true }

# Error Handling
color-eyre = { workspace = true }
thiserror = { workspace = true }

# Async
tokio = { workspace = true }
futures-util = { workspace = true }

# Docker
bollard = { workspace = true }

# Logging
log = { workspace = true }
env_logger = { workspace = true }

# Console/Terminal/CLI
console = { workspace = true }
#crossterm = { workspace = true }
#ratatui = { workspace = true }
comfy-table = { workspace = true }
inquire = "0.7.3"
indicatif = { version = "0.17.8", features = ["improved_unicode"] }
anstyle = { workspace = true }
colorchoice = "1.0.0"
clap = { workspace = true }
clap_complete = { workspace = true }
shellwords = { workspace = true }

# Database
diesel = { workspace = true }
diesel_migrations = { workspace = true }

# Local deps
stackify-common = { path = "../stackify-common" }

# Compression/Archiving
flate2 = { workspace = true }
tar = { workspace = true }